[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-select = [
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
  "E",  # pycodestyle errors
  "I",  # isort
  "UP", # pyupgrade
  "W",  # pycodestyle warnings
]
ignore = ["B905", "D100", "D104"]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
