#! /bin/sh


### start hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

### config

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          8
bspc config top_padding         30
bspc config bottom_padding      0

bspc config presel_feedback_color      '#c8ccd4'
bspc config focused_border_color       '#61afef'
bspc config normal_border_color        '#353b45'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_monocle_padding       12
bspc config right_monocle_padding     0
bspc config bottom_monocle_padding    0
bspc config left_monocle_padding      0

bspc config focus_follows_pointer     true

# remove previous rules
bspc rule -r "*"

bspc rule -a Brave-browser desktop='^1' focus=on
bspc rule -a discord desktop='^10' focus=on

### applications at start up / reload

# polybar
$HOME/.config/polybar/polybar.sh &

# compositor + wallpaper
picom &
feh --bg-fill ~/.background_images/minimalist_nord_arctic.png 
