CompileFlags:
  Add: [-xc++, -std=c++20, -Wall, -Wextra, -Werror, -Wsign-conversion, -Weffc++, -pedantic-errors, -Wno-missing-prototypes]
Diagnostics:
  ClangTidy:
    Add: [performance*, modernize*, readability*]
    Remove: [modernize-use-trailing-return-type]
    CheckOptions:
      readability-identifier-naming.VariableCase: [camelBack, CamelCase]
