return {
  {
    "lukas-reineke/indent-blankline.nvim",
    event = "BufReadPre",
    opts = {

      char = "▎",
      show_current_context = true,
      use_treesitter = true,
      show_current_context_start = true,
      show_trailing_blankline_indent = false,
      filetype_exclude = {
        "lspinfo",
        "packer",
        "checkhealth",
        "help",
        "NvimTree",
        "TelescopePrompt",
        "TelescopeResults",
        "Trouble",
        "startify",
        "neogitstatus",
        "lsp-installer",
        "",
      },
      context_patterns = {
        "class",
        "return",
        "function",
        "method",
        "^if",
        "^while",
        "jsx_element",
        "^for",
        "^object",
        "^table",
        "block",
        "arguments",
        "if_statement",
        "else_clause",
        "jsx_element",
        "jsx_self_closing_element",
        "try_statement",
        "catch_clause",
        "import_statement",
        "operation_type",
      },
    },
  },
}
